@base = https://hapi.fhir.org/baseR4
#@base = https://hapi.fhir.org/baseR5
#@base = https://server.fire.ly
#@base = https://kefhir.kodality.dev/fhir 

###

https://hapi.fhir.org/baseR4/Patient

###

https://hapi.fhir.org/baseR4/Patient/596767

### List of Patient resources
{{base}}/Patient

### Query single resource

{{base}}/Patient/596335

### Simple search by name

{{base}}/Patient?identifier=37302102711

### Simple search by name (output in XML format)

{{base}}/Patient?name=Igor
Content-Type: application/fhir+xml


### Create new patient

POST {{base}}/Patient HTTP/1.1
Content-Type: application/fhir+json

{
  "resourceType" : "Patient",
  "identifier" : [
    {
      "system" : "http://fhir.ee/sid/pid/est",
      "value" : "37302102711"
    }
  ],
  "name" : [{
    "family" : "Bossenko",
    "given" : ["Igor"]
  }],
  "gender" : "male"
}

### Update patient resource

PUT {{base}}/Patient/46659886 HTTP/1.1
Content-Type: application/json

{
  "resourceType" : "Patient",
  "id": "46659886",
  "identifier" : [
    {
      "system" : "http://fhir.ee/sid/pid/est",
      "value" : "37302102711"
    }
  ],
  "name" : [{
    "family" : "Bossenko",
    "given" : ["Igor","Oleg"]
  }],
  "gender" : "male",
  "birthDate": "1973-02-10"
}

###

{{base}}/Patient/46659886/_history/3

###

DELETE {{base}}/Patient/46659886 HTTP/1.1

###

https://hapi.fhir.org/baseR5/Patient/770934/_history/3

### Ask deleted patient

{{base}}/Patient/836034?_pretty=true


###

PUT {{base}}/Patient/770934 HTTP/1.1
Content-Type: application/fhir+xml

<?xml version="1.0" encoding="UTF-8"?>
<Patient xmlns="http://hl7.org/fhir">
    <id value="770934"/>
    <active value="true"/>
    <identifier>
        <system value="http://fhir.ee/sid/pid/est"/>
        <value value="37302102711"/>
    </identifier>
    <name>
        <family value="Bossenko"/>
        <given value="Igor"/>
    </name>
    <gender value="male"/>
    <birthDate value="1973-02-10"/>
</Patient>


### Ask deleted version of patient

{{base}}/Patient/770934/_history/3

### Use files as input for REST operations

PUT {{base}}/Patient/770934 HTTP/1.1
Content-Type: application/json

<@ ./patient2.json

### CapabilityStatement of the FHIR server

{{base}}/CapabilityStatement


### List of patients in XML format

{{base}}/Patient?name=Igor
Accept: application/fhir+json

# Pagination
### List of patients with name John

{{base}}/Patient?name=John
Accept: application/json 

### List of patients with name John with page size 50 patients

{{base}}/Patient?name=John&_count=1
Accept: application/json 

### List of patients with name John from 51 to 100 records

{{base}}/Patient?name=John&_count=50&_page=2
Accept: application/json 


# Advance search
### By gender
{{base}}/Patient?gender=male

###

{{base}}/Patient?family:exact=Rodgers&given=Nor

### By surname and firstname (show FHIRPath)
{{base}}/Patient?name.family=Gusikow&name.given=John

### By exact surname and firstname
{{base}}/Patient?name.family:exact=Gusikowski974&name.given:exact=John


### By identifier
{{base}}/Patient?identifier=37302102711

### 
{{base}}/Patient?identifier=http://politsei.ee|37302102711

### List of observations
{{base}}/Observation

### 3 lates observations of pain measurement. Question - what date used here?
{{base}}/Observation?_sort:desc=date&_count=30

@pid = 2792351

### Pain measurement of patient {{pid}}
{{base}}/Observation?code=http://loinc.org|72514-3
&subject=Patient/{{pid}}

### Look for identifier of Patient
{{base}}/Patient/{{pid}}

### Rewrite search of pain management using patient identifier
{{base}}/Observation?code=http://loinc.org|72514-3
&patient.identifier=https://github.com/synthetichealth/synthea|dc82a7c2-301e-3d59-33ec-6fd84fb3044b


### Pain measurement of patient {{pid}} with patient include
{{base}}/Observation?subject=Patient/44948621
&_count=1
&_include=Observation:subject


### Search for patient with exact id and ask for all him observations
{{base}}/Patient?_id={{pid}}&_revinclude=Observation:subject


### Compartment example
{{base}}/Patient/{{pid}}/Observation


### Updated patient records since 2024-09-19
{{base}}/Patient?_lastUpdated=gt2024-09-19

### All updated records since 2024-09-19
{{base}}?_lastUpdated=gt2024-09-19

