#@base = https://hapi.fhir.org/baseR5
@base = https://termx.taltech.ee/fhir
#@base = https://kefhir.kodality.dev/fhir 

@chef = https://demo.termx.org/chef
//@chef = https://termx.taltech.ee/chef

### V2 FSH -> FHIR

POST {{chef}}/v2/fsh2fhir
Content-Type: application/fsh; version=0.0.1; fhirVersion=5.0.0

<@ ./BloodPressureDefinition.fsh

### V2 FHIR -> FSH

POST {{chef}}/v2/fhir2fsh
Content-Type: application/fhir+json; fhirVersion=5.0.0 

<@ ./BloodPressureDefinitionInArray.json

### Validate the StructureDefinition
POST {{base}}/StructureDefinition/$validate
Content-Type: application/fhir+json

<@ ./BloodPressureDefinition.json

### Upload structure definition to the FHIR server

PUT {{base}}/StructureDefinition/BloodPressure
Content-Type: application/fhir+json

<@ ./BloodPressureDefinition.json

### Query data from the new resource
GET {{base}}/StructureDefinition/BloodPressure

###
{{base}}/Patient?_count=1

@pid = 836034

### Add record to the logical resource type 
# NB! CapabilityStatement should updated first

POST {{base}}/BloodPressure
Content-Type: application/fhir+json

<@ ./BloodPressure.json

###
GET {{base}}/BloodPressure

### CapabilityStatement
{{base}}/CapabilityStatement/base

### Add new CapabilityStatement for logical models
PUT {{base}}/CapabilityStatement/logical-models
Content-Type: application/fhir+json

<@ CapabilityStatement-logical-models.json

### Upload ee-organization profile
PUT {{base}}/StructureDefinition/ee-organization
Content-Type: application/fhir+json

<@ ./ee-organization.json

### Check uploaded profile
{{base}}/StructureDefinition?url=https://fhir.ee/StructureDefinition/ee-organization


### Update *base* CapabilityStatement (DANGER ZONE!!!)
#CapabilityStatement-base-extra.json contains CapabilityStatement-base-origin 
#and type of BloodPressure and new supportedProfile for type Organization
PUT {{base}}/CapabilityStatement/base
Content-Type: application/fhir+json

<@ CapabilityStatement-base-extra.json

### Reread CapabilityStament and 
POST https://kefhir.kodality.dev/conformance-tools/refresh

### Example1 (Rakvere, valid) for ee-organization
POST {{base}}/Organization
Content-Type: application/fhir+json

<@ ./ee-organization-rakvere.json

### Example2 (EHIF, valid) for ee-organization
POST {{base}}/Organization
Content-Type: application/fhir+json

<@ ./ee-organization-ehif.json

### Example2 (EHIF, invalid) for ee-organization
PUT {{base}}/Organization/768792
Content-Type: application/fhir+json

<@ ./ee-organization-ehif-invalid.json

